### ISSUE TITLE
Invisible characters can be used to cheat the character count

### ISSUE THREAD

**Issue by schoentoon** [pbijdens/chatbot#1]
By injecting invisible unicode characters into messages one can influence the character counter dramatically.

Perhaps you shouldn't use plain .Length right here https://github.com/pbijdens/chatbot/blob/master/src/chatbot/ChatStats/GatherStatistics.cs#L99

**Comment by pbijdens** [comment]
One could argue that invisible Unicode characters are characters too, and should be counted as such. However, to keep things fair, prior to counting characters, I'll replace all consecutive *whitespace* characters by a singe space, and trim the message. Invisible characters may still be counted, if they are not whitespace.
